---
- hosts: all
  become: true

  tasks:

    - name: System update
      apt: upgrade=dist update_cache=yes cache_valid_time=3600

    - name: COZOC development tools
      apt: name={{item}} update_cache=yes cache_valid_time=3600
      with_items:
        - synaptic
        - git
        - gnuplot5
        - emacs
        - global
        - python-pygments
        - elpa-helm
        - m4
        - ncview

    - name: COZOC requirements
      apt: name={{item}} update_cache=yes cache_valid_time=3600
      with_items:
        - gcc
        - pkg-config
        - petsc-dev
        - python-sympy
        - cmake
